'use strict';
/* Public, dependency-free design mockup. Every record below is fictional.
   No API clients, secrets, live telemetry, localStorage, or filesystem access. */
const paths = {
  home:'<path d="m3 10 9-7 9 7v11H3Z"/><path d="M9 21v-8h6v8"/>',
  cube:'<path d="m12 2 9 5v10l-9 5-9-5V7Z"/><path d="m3 7 9 5 9-5M12 12v10M7.5 4.5l9 5"/>',
  monitor:'<rect x="3" y="3" width="18" height="13" rx="2"/><path d="M8 21h8M12 16v5M7 7h4"/>',
  server:'<rect x="3" y="2" width="18" height="8" rx="2"/><rect x="3" y="14" width="18" height="8" rx="2"/><path d="M7 6h.01M7 18h.01M11 6h6M11 18h6"/>',
  laptop:'<path d="M5 16V4h14v12M3 16h18l2 4H1Z"/><path d="M10 18h4"/>',
  folder:'<path d="M3 7V4h6l2 3h10v13H3Z"/><path d="M3 9h18"/>',
  skill:'<circle cx="5" cy="5" r="3"/><circle cx="19" cy="5" r="3"/><circle cx="5" cy="19" r="3"/><circle cx="19" cy="19" r="3"/><path d="m7 7 10 10M17 7 7 17"/>',
  tools:'<path d="m12 3 9 5-9 5-9-5Z"/><path d="m3 12 9 5 9-5M3 16l9 5 9-5"/>',
  clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 3"/>',
  book:'<path d="M3 4h6q3 0 3 3 0-3 3-3h6v16h-6q-3 0-3 2-1-2-3-2H3ZM12 7v15M6 8h3M6 12h3M15 8h3M15 12h3"/>',
  settings:'<path d="m9 3 1-2h4l1 2 3 2 3 1 1 4-2 2 0 3 0 3-4 3-3-1-3 0-3 0-3-4 1-3 0-3-1-3 3-3Z"/><circle cx="12" cy="12" r="3.5"/>',
  search:'<circle cx="10.5" cy="10.5" r="7"/><path d="m16 16 5 5"/>',
  bell:'<path d="M18 8a6 6 0 0 0-12 0c0 8-3 8-3 10h18c0-2-3-2-3-10M10 22h4M12 2V1"/>',
  sun:'<circle cx="12" cy="12" r="4"/><path d="M12 1v2M12 21v2M1 12h2M21 12h2M4 4l2 2M18 18l2 2M4 20l2-2M18 6l2-2"/>',
  chevron:'<path d="m9 5 7 7-7 7"/>', down:'<path d="m6 9 6 6 6-6"/>',
  arrow:'<path d="M3 12h18m-6-6 6 6-6 6"/>', up:'<path d="m6 11 6-6 6 6M12 5v15"/>',
  bolt:'<path d="m14 2-10 12h7l-1 8 10-12h-7Z"/>',
  warning:'<path d="M10 3a2 2 0 0 1 4 0l9 16a2 2 0 0 1-2 3H3a2 2 0 0 1-2-3Z"/><path d="M12 8v6M12 18h.01"/>',
  users:'<circle cx="9" cy="7" r="3"/><path d="M3 21v-4a6 6 0 0 1 12 0v4M16 4a3 3 0 0 1 0 6M18 13a5 5 0 0 1 3 5v3"/>',
  grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
  plug:'<path d="M8 2v5M16 2v5M6 7h12v7a6 6 0 0 1-12 0ZM12 20v3"/>',
  tail:'<circle cx="5" cy="5" r="1"/><circle cx="12" cy="5" r="1"/><circle cx="19" cy="5" r="1"/><circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/><circle cx="5" cy="19" r="1"/><circle cx="12" cy="19" r="1"/><circle cx="19" cy="19" r="1"/>',
  window:'<path d="m3 5 8-1v8H3ZM13 4l8-1v9h-8ZM3 14h8v8l-8-1ZM13 14h8v9l-8-1Z" fill="currentColor" stroke="none"/>',
  linux:'<path d="M8 7c0-8 8-8 8 0v6l4 7-6 1-2-3-2 3-6-1 4-7Z"/><path d="m9 9 3 2 3-2M10 5h.01M14 5h.01M9 12l-1 5M15 12l1 5"/>',
  file:'<path d="M5 2h9l5 5v15H5ZM14 2v6h5M8 12h8M8 16h7"/>',
  bulb:'<path d="M9 18c0-3-4-4-4-9a7 7 0 0 1 14 0c0 5-4 6-4 9ZM9 21h6M11 24h2M9 9l3 3 3-3M12 12v6"/>',
  pin:'<path d="m8 3 9 0-2 7 4 4H5l4-4ZM12 14v8"/>',
  copy:'<rect x="8" y="7" width="13" height="15" rx="2"/><path d="M16 7V2H3v15h5"/>',
  swap:'<path d="M3 7h18l-5-5M21 17H3l5 5"/>',
  refresh:'<path d="M20 8a8 8 0 0 0-14-4L3 7M3 2v5h5M4 16a8 8 0 0 0 14 4l3-3M21 22v-5h-5"/>',
  check:'<path d="m5 12 4 4L20 5"/>',
  menu:'<path d="M3 6h18M3 12h18M3 18h18"/>',
  branch:'<circle cx="6" cy="4" r="2"/><circle cx="18" cy="5" r="2"/><circle cx="6" cy="20" r="2"/><path d="M6 6v12M18 7c0 8-12 2-12 10"/>',
  compass:'<circle cx="12" cy="12" r="9"/><path d="m16 8-3 7-6 3 3-7Z"/>',
  wheel:'<circle cx="12" cy="12" r="7"/><circle cx="12" cy="12" r="2"/><path d="M12 1v9M12 14v9M1 12h9M14 12h9M4 4l6 6M14 14l6 6M4 20l6-6M14 10l6-6"/>',
  paperclip:'<path d="m8 16 8-9a3 3 0 0 0-4-4L2 14a5 5 0 0 0 7 7L21 8a7 7 0 0 0-10-10" transform="translate(1 2) scale(.85)"/>',
  download:'<path d="M12 2v14m-6-6 6 6 6-6M3 17v5h18v-5"/>',
  shield:'<path d="m12 2 9 4v7c0 5-9 9-9 9s-9-4-9-9V6Z"/><path d="m7 12 3 3 7-7"/>',
};
document.getElementById('symbols').innerHTML = `<svg xmlns="http://www.w3.org/2000/svg"><defs>${Object.entries(paths).map(([name,path])=>`<symbol id="i-${name}" viewBox="0 0 24 24">${path}</symbol>`).join('')}</defs></svg>`;
const icon=(name,cls='')=>`<svg class="icon ${cls}" aria-hidden="true"><use href="#i-${name}"></use></svg>`;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=s=>document.querySelector(s);
const state={view:'overview',workFilter:'running',agentFilter:'all',noteFilter:'latest',noteQuery:'',left:'unity-01',right:'unity-02',commandIndex:0};
const machines=[
 {id:'main-pc',name:'MainPC',os:'Windows 11',icon:'window',cpu:62,ram:51,address:'100.64.1.12',role:'Unity development',tools:['Oh My Pi','HERDR','Paseo']},
 {id:'worker-01',name:'worker-01',os:'Ubuntu 24.04',icon:'linux',cpu:71,ram:71,address:'100.64.1.22',role:'Build & test worker',tools:['Oh My Pi','Hermes','HERDR']},
 {id:'laptop',name:'laptop',os:'Windows 11',icon:'laptop',cpu:23,ram:36,address:'100.64.1.31',role:'Knowledge & mobile',tools:['Hermes','Paseo']},
 {id:'vps-main',name:'vps-main',os:'Ubuntu 24.04',icon:'server',cpu:34,ram:42,address:'100.64.0.8',role:'Main orchestrator',tools:['Hermes','Oh My Pi','Paperclip','FirstMate']}
];
const agents=[
 {id:'unity-01',machine:'main-pc',runtime:'Oh My Pi',profile:'Unity coder',status:'running',project:'chrono',task:'Implementing sword hit reactions',phase:'Coding',time:'32m',progress:68,model:'Coding model A'},
 {id:'unity-02',machine:'worker-01',runtime:'Oh My Pi',profile:'Unity coder',status:'running',project:'chrono',task:'Adding time-slow regression tests',phase:'Testing',time:'11m',progress:42,model:'Coding model A'},
 {id:'main-agent',machine:'vps-main',runtime:'Hermes',profile:'Orchestrator',status:'running',project:'infrastructure',task:'Reviewing worker capability drift',phase:'Ops',time:'2h',progress:78,model:'Reasoning model B'},
 {id:'researcher',machine:'vps-main',runtime:'Hermes',profile:'Research',status:'running',project:'knowledge',task:'Comparing agent memory patterns',phase:'Research',time:'47m',progress:35,model:'Reasoning model B'},
 {id:'knowledge',machine:'laptop',runtime:'Hermes',profile:'Knowledge',status:'running',project:'knowledge',task:'Organizing project decisions & notes',phase:'Notes',time:'1h',progress:92,model:'Reasoning model B'},
 {id:'animator',machine:'main-pc',runtime:'Oh My Pi',profile:'Unity animator',status:'running',project:'chrono',task:'Tuning enemy attack telegraphs',phase:'Coding',time:'24m',progress:54,model:'Coding model A'},
 {id:'build-worker',machine:'worker-01',runtime:'Hermes',profile:'Build worker',status:'running',project:'infrastructure',task:'Validating reproducible worker setup',phase:'Ops',time:'18m',progress:81,model:'Reasoning model B'},
 {id:'skill-curator',machine:'vps-main',runtime:'Oh My Pi',profile:'Skill curator',status:'running',project:'infrastructure',task:'Reviewing shared skill metadata',phase:'Research',time:'9m',progress:28,model:'Coding model A'},
 {id:'reviewer',machine:'main-pc',runtime:'Oh My Pi',profile:'Code reviewer',status:'idle',project:'infrastructure',task:'Ready for the next review',phase:'Review',time:'6m',progress:0,model:'Coding model A'},
 {id:'test-runner',machine:'worker-01',runtime:'Oh My Pi',profile:'Test runner',status:'blocked',project:'chrono',task:'EditMode suite needs a Unity license',phase:'Testing',time:'12m',progress:23,model:'Coding model A'}
];
const projects=[{id:'chrono',name:'Chrono Blade',kind:'Main development',percent:68,done:'17 / 25 demo milestones',description:'A top-down action RPG built around responsive sword combat and time-manipulation skills.'},{id:'infrastructure',name:'Agent Infrastructure',kind:'Planning',percent:24,done:'6 / 25 demo milestones',description:'A single control plane for machine inventory, agent profiles, shared skills and configuration drift.'},{id:'knowledge',name:'Knowledge Base',kind:'Research',percent:18,done:'2 / 11 demo milestones',description:'Keep decisions, references and ideas close to the work, with an Obsidian-oriented knowledge layer.'}];
const tools=[
 {id:'linear',name:'Linear',icon:'folder',role:'Project work',description:'Issues, milestones and project context. The public mockup contains fictional work only.'},
 {id:'obsidian',name:'Obsidian',icon:'book',role:'Knowledge',description:'Latest notes, important references and quick idea capture. All notes here are fictional.'},
 {id:'onedrive',name:'OneDrive',icon:'folder',role:'Files & artifacts',description:'Conceptual links to assets, builds and reference files. No folders are connected.'},
 {id:'todoist',name:'Todoist',icon:'check',role:'Personal tasks',description:'A place for personal actions without duplicating the development backlog.'},
 {id:'paseo',name:'Paseo',icon:'compass',role:'Remote access',description:'A planned entry point to remote agent sessions. No remote session is exposed here.'},
 {id:'paperclip',name:'Paperclip',icon:'paperclip',role:'Goals & governance',description:'Organizational goals, review context and oversight. No tasks are dispatched from this demo.'},
 {id:'hermes',name:'Hermes',icon:'bolt',role:'Agent runtime',description:'General-purpose agents and the main VPS orchestrator are represented by simulated profiles.'},
 {id:'omp',name:'oh my pi',icon:'branch',role:'Coding runtime',description:'Unity coding, test and review agents with comparable settings and shared skills.'},
 {id:'herdr',name:'HERDR',icon:'branch',role:'Session visibility',description:'A planned session inspection surface. Not a coding agent or a skill itself.'},
 {id:'firstmate',name:'FirstMate',icon:'wheel',role:'Delegation',description:'Supervision and delegation context. Represented separately from worker agents.'},
 {id:'discord',name:'Discord',icon:'users',role:'Communication',description:'Notifications and conversation entry points. No channels or messages are connected.'},
 {id:'tailscale',name:'Tailscale',icon:'tail',role:'Private network',description:'A simulated four-machine network. Addresses are examples, not a live tailnet inventory.'}
];
function logo(id){
 let s;
 if(id==='obsidian')s='<path d="m13 1 8 8-4 15-10-2L3 12 7 6Z" fill="#aa80fa"/><path d="m13 1 1 9-7 12-4-10 4-6Z" fill="#663de0"/><path d="m14 10 7-1-4 15-10-2Z" fill="#b994ff"/><path d="m14 10 3 14-10-2Z" fill="#7954e8"/>';
 else if(id==='linear')s='<circle cx="12" cy="12" r="10" fill="#ddd7ff"/><path d="m3 8 13 13M2 12l10 10M5 4l15 15M9 2l13 13" stroke="#6551e7" stroke-width="1.8"/>';
 else if(id==='onedrive')s='<path d="M6 16a7 7 0 0 1 14-7 5 5 0 0 1 1 10H6Z" fill="#008ded"/><path d="M2 11a5 5 0 0 1 8-1 5 5 0 0 1 3 9H4a4 4 0 0 1-2-8" fill="#32b8ff"/><path d="m9 13 10-4a5 5 0 0 1 2 10H6Z" fill="#0877d5"/>';
 else if(id==='todoist')s='<path d="m3 6 6 3 12-7M3 12l6 3 12-7M3 18l6 3 12-7" fill="none" stroke="white" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>';
 else if(id==='discord')s='<path d="M5 5 9 4l1 2h4l1-2 4 1c3 4 4 8 3 13l-5 2-2-3H9l-2 3-5-2C1 13 2 9 5 5" fill="#edf1ff"/><ellipse cx="8" cy="12" rx="2" ry="2.5" fill="#6256e9"/><ellipse cx="16" cy="12" rx="2" ry="2.5" fill="#6256e9"/>';
 else if(id==='hermes')s='<path d="M3 20V4l9 10 9-10v16M3 4l3 11M21 4l-3 11" fill="none" stroke="#edf3ff" stroke-width="2.3" stroke-linecap="round"/>';
 else if(id==='tailscale')s=Array.from({length:9},(_,k)=>`<circle cx="${5+(k%3)*7}" cy="${5+Math.floor(k/3)*7}" r="2" fill="${k<3?'#72819b':'#d6deee'}"/>`).join('');
 else return `<span class="app-logo ${id}">${icon((tools.find(t=>t.id===id)||{}).icon||'cube')}</span>`;
 return `<span class="app-logo ${id}"><svg viewBox="0 0 24 26" aria-hidden="true">${s}</svg></span>`;
}
const skills=[{id:'unity-coding',short:'Code',version:'1.4.2'},{id:'unity-tests',short:'Tests',version:'1.1.5'},{id:'web-research',short:'Research',version:'1.8.1'},{id:'obsidian-notes',short:'Notes',version:'0.2.0'},{id:'node-ops',short:'Ops',version:'1.0.0'},{id:'task-planning',short:'Plan',version:'1.3.0'},{id:'unity-debugging',short:'Debug',version:'1.2.0'},{id:'git-workflow',short:'Git',version:'2.0.1'}];
const skillStates={
 'unity-01':['same','same','unassigned','missing','unassigned','same','same','same'],
 'unity-02':['modified','missing','unassigned','unassigned','unassigned','same','modified','same'],
 reviewer:['same','same','same','unassigned','unassigned','same','same','same'],
 'main-agent':['unassigned','unassigned','same','same','same','same','unassigned','same'],
 researcher:['unassigned','unassigned','same','same','unassigned','same','unassigned','same'],
 knowledge:['unassigned','unassigned','same','same','unassigned','same','unassigned','same'],
 animator:['same','same','unassigned','unassigned','unassigned','same','same','same'],
 'build-worker':['unassigned','same','unassigned','unassigned','same','same','same','same'],
 'skill-curator':['same','same','same','unassigned','same','same','same','same'],
 'test-runner':['same','same','unassigned','unassigned','same','same','same','same']
};
const miniAgents=['unity-01','unity-02','reviewer','main-agent','researcher','knowledge'];
const stateNames={same:'Installed',modified:'Modified',missing:'Required but missing',unassigned:'Not assigned'};
let notes=[
 {id:'harness',title:'Control plane principles',folder:'Agent Harness',time:'18m ago',pinned:true,type:'note',body:'One place to see the whole system.\n\nKeep the dashboard focused on inventory, differences and decisions. Agent runtimes execute work; the dashboard helps the human understand and supervise it.\n\nA profile is not a process. An installed skill is not proof that a running session loaded it. Show the distinction.\n\nSample design note — not read from a real vault.'},
 {id:'combat',title:'Combat readability & hit-stop',folder:'Chrono Blade / Combat',time:'42m ago',pinned:true,type:'note',body:'Make a sword hit feel immediate without making enemy attacks difficult to read.\n\nNext experiment: test three hit-stop durations while keeping the enemy telegraph unchanged. Capture one short gameplay clip per variant.\n\nTime slow should change the rhythm of combat, not hide unclear animations.\n\nSample design note — not read from a real vault.'},
 {id:'unity',title:'Unity workflow constraints',folder:'Chrono Blade / Engineering',time:'1h ago',pinned:true,type:'note',body:'Keep each change small enough to play-test.\n\nDo not mark a gameplay feature done from a code diff alone. Record which test or playable scenario was used, what passed and what still needs a human check.\n\nSample workflow note.'},
 {id:'template',title:'OMP Unity skill template',folder:'AI / Skills',time:'2h ago',pinned:false,type:'note',body:'A skill needs a clear trigger, scope, expected inputs and completion evidence.\n\nState the project constraints explicitly. Avoid duplicating repository conventions across multiple skills.\n\nThis is a fictional note for testing the knowledge interface.'},
 {id:'naming',title:'Agent naming & ownership',folder:'Agent Harness / Decisions',time:'3h ago',pinned:false,type:'note',body:'Use stable agent profile IDs and separate machine IDs.\n\nA session can move to another machine without changing the identity of its reusable profile.\n\nSample architecture note.'},
 {id:'inbox',title:'Idea: a calmer attention queue',folder:'00 Inbox',time:'Yesterday',pinned:false,type:'idea',body:'Only escalate drift that changes an agent’s expected capabilities. Keep harmless local differences visible but quiet.\n\nMock idea, ready for a future design review.'}
];
const events=[
 {icon:'warning',title:'Test runner needs a Unity license',body:'worker-01 / test-runner · The EditMode suite is blocked. No restart or licensing action has been performed.',time:'12m ago',agent:'test-runner'},
 {icon:'swap',title:'Unity skill differs from its profile',body:'worker-01 / unity-02 · unity-coding and unity-debugging contain local changes. Compare before copying.',time:'31m ago',agent:'unity-02'},
 {icon:'check',title:'Enemy telegraph pass ready for review',body:'MainPC / animator · A sample animation task reached its human-review step.',time:'43m ago'},
 {icon:'folder',title:'Chrono Blade milestone updated',body:'Linear · The fictional vertical-slice checklist is now at 17 of 25 milestones.',time:'1h ago'},
 {icon:'users',title:'Review context prepared',body:'FirstMate · Proposed a bounded reviewer task. No autonomous dispatch in the public mockup.',time:'2h ago'},
 {icon:'book',title:'Control plane note pinned',body:'Obsidian concept · A key decision is now included in Important notes.',time:'3h ago'}
];
const configOverrides={};
function config(id){const a=agents.find(x=>x.id===id);return {...{Runtime:a.runtime,Model:a.model,Reasoning:a.runtime==='Hermes'?'Medium':'High',Browser:a.runtime==='Hermes'?'Enabled':'Disabled','HERDR access':'Enabled','Installed skills':String(skillStates[id].filter(s=>s==='same'||s==='modified').length),Hooks:id==='unity-02'?'5':'6',Permissions:a.runtime==='Hermes'?'Approval-gated tools':'Project workspace',Profile:a.profile},...(configOverrides[id]||{})};}
const nav=[['overview','home','Overview'],['agents','cube','Agents'],['machines','monitor','Machines'],['projects','folder','Projects'],['skills','skill','Skills'],['integrations','tools','Tools & Integrations'],['activity','clock','Activity'],['knowledge','book','Knowledge'],['settings','settings','Settings']];
$('#navigation').innerHTML=nav.map(([id,i,label])=>`<a class="nav-link" href="#${id}" data-nav="${id}" title="${label}">${icon(i)}<span>${label}</span></a>`).join('');
$('#search-icon').innerHTML=icon('search');$('#bell-icon').innerHTML=icon('bell');$('#capture-trigger').innerHTML=icon('bulb');$('#profile-chevron').innerHTML=icon('down');$('#atmosphere').innerHTML=icon('sun');$('#menu-button').innerHTML=icon('menu');
function heading(eyebrow,title,copy,actions=''){return `<section class="page-heading"><div><div class="eyebrow">${esc(eyebrow)}</div><h1>${esc(title)}</h1><p>${esc(copy)}</p></div>${actions?`<div class="page-actions">${actions}</div>`:''}</section>`;}
function button(label,action,id='',cls='',i=''){return `<button class="button ${cls}" data-action="${action}" data-id="${esc(id)}">${i?icon(i):''}${label}</button>`;}
function panelHead(i,title,sub,action='',label='',id='',tone=''){return `<div class="panel-head"><div class="panel-title"><span class="title-glyph ${tone}">${icon(i)}</span><div><h2>${title}</h2><p>${sub}</p></div></div>${action?button(label,action,id,'small'):''}</div>`;}
const installed=id=>skillStates[id].filter(s=>s==='same'||s==='modified').length;
const machineFor=id=>machines.find(m=>m.id===id);
function meter(name,value,hot=false){return `<span class="micro-meter">${name}<span class="micro-track"><i class="${hot?'hot':''}" style="width:${value}%"></i></span><small>${value}%</small></span>`;}
function miniMachine(m){return `<button class="machine-mini" data-action="machine" data-id="${m.id}" aria-label="Inspect ${m.name}"><span class="machine-mini-header"><span class="os-icon ${m.icon}">${icon(m.icon)}</span><span><h3>${m.name}</h3><span class="address">${m.address}</span></span><span class="circle-chevron">${icon('chevron')}</span></span><span class="online-label"><i class="led"></i>Online</span><span class="machine-tags"><span>${icon('tail')}Tailscale</span><span>${icon('users')}${agents.filter(a=>a.machine===m.id).length} agents</span></span><span class="machine-meters">${meter('CPU',m.cpu,m.id==='worker-01')}${meter('RAM',m.ram)}</span></button>`;}
function workPills(){return `<div class="filter-pills">${[['all','All'],['running','Running'],['idle','Idle'],['blocked','Blocked']].map(([id,label])=>`<button class="${state.workFilter===id?'active':''}" data-action="work-filter" data-id="${id}" aria-pressed="${state.workFilter===id}">${label}<span class="${id==='blocked'?'blocked-count':''}">${id==='all'?agents.length:agents.filter(a=>a.status===id).length}</span></button>`).join('')}</div>`;}
function workRows(){const list=agents.filter(a=>state.workFilter==='all'||a.status===state.workFilter);return `<div class="work-rows">${list.slice(0,5).map((a,k)=>`<button class="work-row" data-action="agent" data-id="${a.id}" aria-label="Inspect ${a.id}: ${esc(a.task)}"><span class="led ${a.status==='blocked'?'red':a.status==='idle'?'idle':''}"></span><span class="agent-icon ${k>1?'teal':''}">${icon(a.machine==='vps-main'?'server':a.machine==='laptop'?'laptop':'monitor')}</span><span class="work-name"><strong>${machineFor(a.machine).name}</strong><small>${a.runtime==='Oh My Pi'?'oh my pi':a.runtime} · ${a.id==='main-agent'?'main':a.id}</small></span><span class="work-task">${esc(a.task)}</span><span class="work-type ${a.phase.toLowerCase()}">${a.phase}</span><span class="work-progress"><i style="width:${a.progress}%"></i></span><time>${a.time}</time><span class="row-more">···</span></button>`).join('')}</div><div class="work-footer"><span>Showing ${Math.min(5,list.length)} of ${list.length} ${state.workFilter==='all'?'':state.workFilter+' '}sessions · simulated</span><button data-action="go" data-id="agents">View all agents →</button></div>`;}
function miniSkills(){return `<div class="skill-mini-wrap"><table class="skill-mini"><thead><tr><th>Agent</th>${skills.slice(0,6).map(s=>`<th>${s.short}</th>`).join('')}</tr></thead><tbody>${miniAgents.map(id=>`<tr><td>${id}</td>${skills.slice(0,6).map((s,k)=>`<td><button data-action="skill" data-id="${id}|${k}" aria-label="${id}, ${s.id}: ${stateNames[skillStates[id][k]]}" title="${s.id} · ${stateNames[skillStates[id][k]]}"><span class="skill-dot ${skillStates[id][k]}"></span></button></td>`).join('')}</tr>`).join('')}</tbody></table></div>${skillLegend()}`;}
function skillLegend(){return `<div class="skill-mini-legend"><span><i class="skill-dot"></i>Installed</span><span><i class="skill-dot modified"></i>Modified</span><span><i class="skill-dot missing"></i>Missing</span><span><i class="skill-dot unassigned"></i>Not assigned</span></div>`;}
function miniTools(){return `<div class="tools-mini">${tools.map(t=>`<button class="tool-mini" data-action="tool" data-id="${t.id}" aria-label="${t.name}: simulated integration">${logo(t.id)}<span><strong>${t.name}</strong><small><i class="led"></i>${t.id==='tailscale'?'4 mock PCs':'Demo ready'}</small></span></button>`).join('')}</div><div class="tools-footer">${button('Add integration','notice','Connections are intentionally unavailable in this public mockup.','', 'plug')}${button('Manage all tools →','go','integrations','text')}</div>`;}
function overview(){return `<section class="hero"><div><h1>Good evening, <span>Michał.</span></h1><p>Your agent ecosystem, in one place. Here’s what matters right now.</p></div><blockquote>“A well-orchestrated mind<br>multiplies itself.”<small>— Your Future Self</small></blockquote></section>
 <section class="metrics" aria-label="Simulated harness summary">
  <article class="metric red"><div class="metric-top"><span class="metric-emblem">${icon('warning')}</span><div><div class="metric-label">Urgent Issues</div><div class="metric-value">2</div><div class="metric-description">1 blocked · 1 config drift</div></div></div><button class="metric-open" data-action="attention" aria-label="Review urgent issues">${icon('chevron')}</button><div class="metric-details"><button data-action="agent" data-id="test-runner"><i class="led red"></i><strong>test-runner</strong><span>Unity license required</span><time>12m ago</time></button><button data-action="go" data-id="settings"><i class="led red"></i><strong>unity-02</strong><span>Skill profile has drifted</span><time>31m ago</time></button></div></article>
  <article class="metric purple"><div class="metric-top"><span class="metric-emblem">${icon('bolt')}</span><div><div class="metric-label">Running Agents</div><div class="metric-value">8 <small>/ 10</small></div><div class="metric-description">agents active</div></div></div><button class="metric-open" data-action="go" data-id="agents" aria-label="View running agents">${icon('chevron')}</button><svg class="agent-spark" viewBox="0 0 240 43" preserveAspectRatio="none" aria-label="Illustrative agent activity"><defs><linearGradient id="sparkfade" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#9360ef" stop-opacity=".15"/><stop offset="1" stop-color="#9360ef" stop-opacity="0"/></linearGradient></defs><path d="M1 33C8 23 13 36 22 30S31 12 43 20 51 25 60 15 79 15 91 19 108 26 124 19 147 22 158 24 176 22 184 19 205 9 219 5 233 3 239 1V43H0Z" fill="url(#sparkfade)"/><path d="M1 33C8 23 13 36 22 30S31 12 43 20 51 25 60 15 79 15 91 19 108 26 124 19 147 22 158 24 176 22 184 19 205 9 219 5 233 3 239 1" fill="none" stroke="#a769f6" stroke-width="1.6"/><circle cx="184" cy="19" r="5" fill="#a878ee" opacity=".25"/><circle cx="184" cy="19" r="2.8" fill="#d7afff"/></svg><div class="metric-foot">${icon('up')}+2 from yesterday <span class="sr-only">in this fictional scenario</span></div></article>
  <article class="metric blue"><div class="metric-top"><span class="metric-emblem">${icon('folder')}</span><div><div class="metric-label">Active Projects</div><div class="metric-value">3</div><div class="metric-description">in progress</div></div></div><button class="metric-open" data-action="go" data-id="projects" aria-label="View projects">${icon('chevron')}</button><div class="metric-projects">${projects.map((p,k)=>`<button data-action="project" data-id="${p.id}"><i class="led" style="background:${['#16e2b7','#36cde6','#5694ff'][k]}"></i><strong>${p.name}</strong><span>${p.kind}</span><span>${p.percent}%</span></button>`).join('')}</div></article>
  <article class="metric teal"><div class="metric-top"><span class="metric-emblem">${icon('monitor')}</span><div><div class="metric-label">Machines Online</div><div class="metric-value">4 <small>/ 4</small></div><div class="metric-description">Tailscale connected · demo</div></div></div><button class="metric-open" data-action="go" data-id="machines" aria-label="View machines">${icon('chevron')}</button><div class="equalizer" aria-hidden="true">${[24,31,27,29,34,30,28,33,29,32,26,34,29,30,27,34,29,31].map(h=>`<i style="height:${h}px"></i>`).join('')}</div><div class="metric-foot"><i class="led"></i>All four demo nodes reachable</div></article>
 </section>
 <div class="middle-grid"><section class="panel work-panel"><div class="panel-head"><div class="panel-title"><span class="bolt-glyph">${icon('bolt')}</span><div><h2>Active Work</h2><p>Your agents, tasks and current context</p></div></div>${workPills()}</div>${workRows()}</section>
 <section class="panel focus-panel"><img class="focus-art" src="./assets/focus.webp" alt="" width="234" height="200"><div class="focus-kicker"><span class="mini-icon">${icon('file')}</span>Current Focus</div><div class="focus-name">${logo('obsidian')}<div><h2>Chrono Blade</h2><p>Time-bending action RPG</p></div></div><p class="focus-copy">Building the vertical slice: responsive sword combat, readable enemies and time-manipulation skills.</p><div class="focus-progress" aria-label="68 percent of demo milestones"><span class="track"><i></i></span><strong>68%</strong></div><div class="focus-chips"><button data-action="project" data-id="chrono">${icon('users')}4 agents</button><button data-action="go" data-id="machines">${icon('monitor')}MainPC, worker-01</button><button data-action="tool" data-id="linear">${icon('folder')}Linear</button><button data-action="go" data-id="knowledge">${icon('book')}Obsidian</button></div><div class="focus-actions">${button('View in Linear','notice','Linear is a design placeholder here. No live project is connected.','primary','cube')}${button('View Project','project','chrono','','folder')}</div><div class="focus-vertical">BOLDER<br>AGENTS<br>BIGGER<br>WORLDS</div><div class="focus-quote">“Small agents.<br>Big adventures.”</div></section></div>
 <div class="lower-grid"><section class="panel machines-panel">${panelHead('monitor','Machines','4 machines · Tailscale network','go','Manage','machines')}<div class="machine-minis">${machines.map(miniMachine).join('')}</div></section><section class="panel skill-panel">${panelHead('grid','Skill Matrix','Shared skills across your agents','go','Manage Skills','skills','purple')}${miniSkills()}</section><section class="panel tools-panel">${panelHead('plug','Integrations & Tools','Your connected-tool design inventory','','','','teal')}${miniTools()}</section></div>`;}
function agentsPage(){let list=agents.filter(a=>state.agentFilter==='all'||a.status===state.agentFilter);return heading('RUNTIME / AGENTS','Your team, across machines.','10 fictional agents · 8 running · 1 idle · 1 blocked',button('Compare configurations','go','settings','','swap'))+`<div class="page-toolbar"><div class="note-tabs">${['all','running','idle','blocked'].map(s=>`<button data-action="agent-filter" data-id="${s}" class="${state.agentFilter===s?'active':''}">${s[0].toUpperCase()+s.slice(1)} · ${s==='all'?agents.length:agents.filter(a=>a.status===s).length}</button>`).join('')}</div><span class="eyebrow">SIMULATED INVENTORY</span></div><section class="panel table-scroll"><table class="data-table"><thead><tr><th>Agent</th><th>Status</th><th>Machine</th><th>Runtime / profile</th><th>Skills</th><th>Current task</th><th></th></tr></thead><tbody>${list.map(a=>`<tr><td>${a.id}</td><td><span class="state-pill ${a.status}">${a.status}</span></td><td>${machineFor(a.machine).name}</td><td>${a.runtime} / ${a.profile}</td><td>${installed(a.id)}</td><td>${a.task}</td><td>${button('Inspect','agent',a.id,'small','chevron')}</td></tr>`).join('')}</tbody></table></section>`;}
function machinesPage(){return heading('INFRASTRUCTURE / TAILSCALE','One fleet. Every machine.','See the control plane, worker machines and their installed runtimes.',button('Network details','notice','These four addresses and health readings are fictional. No Tailscale API is connected.','','tail'))+`<div class="fleet-grid">${machines.map(m=>`<section class="panel fleet-card"><div class="machine-mini-header"><span class="os-icon ${m.icon}">${icon(m.icon)}</span><div><h3>${m.name}</h3><p class="address">${m.os} · ${m.address}</p></div><span class="state-pill" style="margin-left:auto">Online · demo</span></div><p class="fleet-info"><span>${m.role}</span><span>${agents.filter(a=>a.machine===m.id).length} agents</span></p><div class="focus-chips">${m.tools.map(t=>`<button data-action="notice" data-id="${esc(t+' is represented by sample data, not a connected service.')}">${esc(t)}</button>`).join('')}</div><div class="machine-meters">${meter('CPU',m.cpu,m.id==='worker-01')}${meter('RAM',m.ram)}</div><div class="card-actions">${button('Inspect machine','machine',m.id,'','monitor')}${button('Compare configs','go','settings','','swap')}</div></section>`).join('')}</div>`;}
function projectsPage(){return heading('WORK / PROJECTS','Keep the outcome in focus.','Three sample projects with explicit agent assignments and related context.')+`<div class="project-cards">${projects.map(p=>`<section class="panel project-card"><span class="eyebrow">${p.kind}</span><h2>${p.name}</h2><p>${p.description}</p><div class="track"><i style="width:${p.percent}%"></i></div><small>${p.percent}% · ${p.done}</small><div class="card-actions">${button('View project','project',p.id,'primary','folder')}${button('Notes','go','knowledge','','book')}</div></section>`).join('')}</div>`;}
function skillsPage(){return heading('CAPABILITIES / REGISTRY','Who has what. And what differs.','Compare installed skills, profile drift and missing capabilities.',button('Compare agent settings','go','settings','','swap'))+`<section class="panel"><div class="panel-head"><div class="panel-title"><span class="title-glyph purple">${icon('grid')}</span><div><h2>Skill coverage</h2><p>Select any cell to inspect it or simulate a registry copy.</p></div></div></div><div class="table-scroll"><table class="skill-full"><thead><tr><th>Skill / registry version</th>${miniAgents.map(id=>`<th>${id}</th>`).join('')}</tr></thead><tbody>${skills.map((s,k)=>`<tr><td><strong>${s.id}</strong><small>v${s.version}</small></td>${miniAgents.map(id=>`<td><button data-action="skill" data-id="${id}|${k}" aria-label="${id}, ${s.id}: ${stateNames[skillStates[id][k]]}"><span class="skill-dot ${skillStates[id][k]}"></span></button></td>`).join('')}</tr>`).join('')}</tbody></table></div>${skillLegend()}<p class="skills-explainer">Installed is not a quality score. Modified means local content differs; missing means the profile expects a skill that is absent. “Not assigned” is an intentional difference. Copy operations only change this tab’s demo data.</p></section>`;}
function toolsPage(){return heading('ECOSYSTEM / TOOLS','Specialized tools. One working view.','Every connection below is a placeholder. Nothing exposes your private harness.')+`<div class="integration-cards">${tools.map(t=>`<section class="panel integration-card"><div class="integration-head">${logo(t.id)}<div><h2>${t.name}</h2><small>${t.role}</small></div></div><p>${t.description}</p><small>SIMULATED · NOT CONNECTED</small><div class="card-actions">${button(t.id==='obsidian'?'Explore demo notes':'Inspect integration',t.id==='obsidian'?'go':'tool',t.id==='obsidian'?'knowledge':t.id,'',t.icon)}</div></section>`).join('')}</div>`;}
function filteredNotes(){return notes.filter(n=>(state.noteFilter==='latest'||(state.noteFilter==='important'?n.pinned:n.type==='idea'))&&`${n.title} ${n.body} ${n.folder}`.toLowerCase().includes(state.noteQuery.toLowerCase()));}
function notesList(){return filteredNotes().map(n=>`<article class="note-card"><button class="note-open" data-action="note" data-id="${n.id}"><strong>${esc(n.title)}</strong><p>${esc(n.body.split('\n')[0])}</p><small>${esc(n.folder)} · ${esc(n.time)} · ${n.type}</small></button><button class="pin-button ${n.pinned?'pinned':''}" data-action="pin" data-id="${n.id}" aria-label="${n.pinned?'Unpin':'Pin'} ${esc(n.title)}" aria-pressed="${n.pinned}">${n.pinned?'★':'☆'}</button></article>`).join('')||'<p class="empty-state">No demo notes match your search.</p>';}
function knowledgePage(){return heading('KNOWLEDGE / OBSIDIAN','Your thinking, within reach.','Recent notes, important decisions and ideas—without leaving the dashboard.',button('Capture idea','capture','','primary','bulb'))+`<div class="page-toolbar"><input class="filter-input" id="notes-search" value="${esc(state.noteQuery)}" placeholder="Search demo notes…" aria-label="Search demo notes"><span class="eyebrow">FICTIONAL VAULT / WORK</span></div><div class="notes-grid"><section class="panel"><div class="panel-head"><div class="panel-title"><span class="title-glyph purple">${icon('book')}</span><div><h2>Your notes</h2><p>${notes.length} notes in the demo vault</p></div></div><div class="note-tabs">${[['latest','Latest'],['important','Important'],['ideas','Ideas']].map(([id,label])=>`<button data-action="note-filter" data-id="${id}" class="${state.noteFilter===id?'active':''}">${label}</button>`).join('')}</div></div><div class="note-list" id="notes-list">${notesList()}</div></section><div><section class="panel">${panelHead('pin','Important & pinned','Decisions worth keeping close','','','','purple')}<div class="pinned-list">${notes.filter(n=>n.pinned).map(n=>`<button class="pinned-row" data-action="note" data-id="${n.id}">${icon('file')}${esc(n.title)}</button>`).join('')||'<p class="empty-state">Pin a note to keep it here.</p>'}</div></section><section class="panel capture-card"><span class="eyebrow">QUICK CAPTURE / CTRL I</span><h2>Make room for the next idea.</h2><p>Create a new demo inbox note, or append an idea to an existing project note. Export it as Markdown when you are ready.</p>${button('Add an idea…','capture','','primary','bulb')}<p class="demo-notice">No Obsidian vault is connected. Your changes stay in memory in this tab and disappear on reload.</p></section></div></div>`;}
function activityPage(){return heading('ACTIVITY / ATTENTION','Only the changes that matter.','A simulated timeline of decisions, blocked work and capability changes.')+`<section class="panel"><div class="activity-list">${events.map((e,k)=>`<article class="event-row"><span>${icon(e.icon)}</span><div><h3>${e.title}</h3><p>${e.body}</p>${k<2?`<div class="card-actions">${button('Review',k===0?'agent':'go',k===0?'test-runner':'settings','small')}</div>`:''}</div><time>${e.time}</time></article>`).join('')}</div></section>`;}
function settingsPage(){const l=config(state.left),r=config(state.right);const rows=Object.keys(l);return heading('SETTINGS / CONFIGURATION','Compare the intent, not just the file.','A semantic comparison of two fictional agent profiles.',button('View raw comparison','raw','','','file'))+`<div class="compare-layout"><section class="panel compare-selectors"><h2>Compare agents</h2><label>Source<select id="compare-left">${agents.map(a=>`<option value="${a.id}" ${a.id===state.left?'selected':''}>${a.id} / ${machineFor(a.machine).name}</option>`).join('')}</select></label><label>Target<select id="compare-right">${agents.map(a=>`<option value="${a.id}" ${a.id===state.right?'selected':''}>${a.id} / ${machineFor(a.machine).name}</option>`).join('')}</select></label>${button('Swap sides','swap','','','swap')}<p class="demo-notice">Differences can be intentional. Review the affected settings before applying a simulated copy.</p></section><section class="panel"><div class="panel-head"><div class="panel-title"><span class="title-glyph purple">${icon('swap')}</span><div><h2>Configuration compare</h2><p>${rows.filter(k=>l[k]!==r[k]).length} differences · ${state.left} → ${state.right}</p></div></div></div><div class="table-scroll"><table class="data-table compare-table"><thead><tr><th>Setting</th><th>${state.left}</th><th>${state.right}</th><th>State</th></tr></thead><tbody>${rows.map(k=>`<tr><td>${k}</td><td>${esc(l[k])}</td><td class="${l[k]!==r[k]?'diff':'same'}-value">${esc(r[k])}</td><td>${l[k]!==r[k]?'Different':'Same'}</td></tr>`).join('')}</tbody></table></div><div class="full-panel">${button('Review settings copy','copy-config','','primary','copy')}<p class="demo-notice" style="margin-top:13px">Profile identity, runtime, permissions and skills are not blindly copied. The demo only lets you copy model, reasoning and browser preferences.</p></div></section></div>`;}
const pageRenderers={overview,agents:agentsPage,machines:machinesPage,projects:projectsPage,skills:skillsPage,integrations:toolsPage,activity:activityPage,knowledge:knowledgePage,settings:settingsPage};
function render(){document.querySelectorAll('[data-nav]').forEach(a=>{a.classList.toggle('active',a.dataset.nav===state.view);if(a.dataset.nav===state.view)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('#main').innerHTML=pageRenderers[state.view]();document.title=`HARNESS · ${nav.find(n=>n[0]===state.view)[2]} · Mockup`;}
function go(view){if(!pageRenderers[view])return;closeDialogs();$('#sidebar').classList.remove('open');$('#menu-button').setAttribute('aria-expanded','false');if(location.hash==='#'+view){state.view=view;render();}else location.hash=view;window.scrollTo({top:0,behavior:'instant'});}
window.addEventListener('hashchange',()=>{const name=location.hash.slice(1);state.view=pageRenderers[name]?name:'overview';render();$('#sidebar').classList.remove('open');$('#menu-button').setAttribute('aria-expanded','false');});
function closeDialogs(){document.querySelectorAll('dialog[open]').forEach(d=>d.close());}
function detail(title,kicker,body,actions=''){closeDialogs();$('#detail-content').innerHTML=`<div class="dialog-heading"><div><span class="eyebrow">${esc(kicker)}</span><h2 id="detail-title">${esc(title)}</h2></div><button class="icon-button close-dialog" data-close="detail-dialog" aria-label="Close inspector">×</button></div><div class="dialog-body">${body}</div>${actions?`<div class="dialog-actions">${actions}</div>`:''}`;$('#detail-dialog').showModal();}
function detailsGrid(obj){return `<div class="detail-grid">${Object.entries(obj).map(([k,v])=>`<div><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')}</div>`;}
function inspectAgent(id){const a=agents.find(a=>a.id===id);if(!a)return;detail(a.id,'AGENT / SIMULATED SESSION',`<p>${esc(a.task)}</p>${detailsGrid({Status:a.status,Machine:machineFor(a.machine).name,Runtime:a.runtime,Profile:a.profile,'Installed skills':installed(a.id),Project:projects.find(p=>p.id===a.project).name})}<p class="demo-notice">This is a fictional agent session. There is no connection to a process, terminal or private machine.</p>`,button('Compare settings','compare-agent',id,'','swap')+button('Open in HERDR','notice','HERDR is not connected in this public design mockup.','','branch'));}
function inspectMachine(id){const m=machineFor(id);if(!m)return;detail(m.name,'MACHINE / DEMO INVENTORY',`<p>${m.role}</p>${detailsGrid({'Operating system':m.os,'Example tailnet address':m.address,CPU:m.cpu+'%',RAM:m.ram+'%','Installed tools':m.tools.join(', '),'Assigned agents':agents.filter(a=>a.machine===m.id).map(a=>a.id).join(', ')})}<p class="demo-notice">Example addresses and telemetry only. No live network checks or remote actions are performed.</p>`,button('View agents','go','agents','','users'));}
function inspectProject(id){const p=projects.find(p=>p.id===id);if(!p)return;detail(p.name,'PROJECT / SAMPLE WORK',`<p>${p.description}</p>${detailsGrid({Progress:p.percent+'% of fictional milestones',Checklist:p.done,Agents:agents.filter(a=>a.project===p.id).map(a=>a.id).join(', '),Context:p.id==='chrono'?'Combat readability · Unity workflow':'Control plane principles'})}<p class="demo-notice">Milestones and activity are sample data, not a statement about your actual project progress.</p>`,button('Related notes','go','knowledge','','book')+button('View agents','go','agents','','users'));}
function inspectTool(id){const t=tools.find(t=>t.id===id);if(!t)return;detail(t.name,'INTEGRATION / DESIGN PLACEHOLDER',`<div class="integration-head">${logo(t.id)}<strong>${t.role}</strong></div><p style="margin-top:16px">${t.description}</p><p class="demo-notice">Not connected. No credentials, private configuration, vault content or live API access are included in this public repository.</p>`,t.id==='obsidian'?button('Explore notes','go','knowledge','primary','book'):button('View all tools','go','integrations','','plug'));}
function inspectSkill(value){const [id,kText]=value.split('|'),k=Number(kText),s=skills[k];if(!s||!skillStates[id])return;const status=skillStates[id][k];detail(s.id,'SKILL / COMPARE & COPY',`<p>${esc(id)} · ${stateNames[status]}</p>${detailsGrid({Registry:'v'+s.version,Agent:id,Installation:stateNames[status],'Operation scope':'This browser tab only'})}<p>${status==='modified'?'This fixture represents a local change. A real adapter would show the exact file diff before any overwrite.':status==='missing'?'The sample profile expects this skill, but the agent does not have it installed.':status==='unassigned'?'This skill is not assigned to the sample profile. Different capabilities can be intentional.':'The sample installation matches its registry version.'}</p><p class="demo-notice">“Copy registry version” changes this demo cell only. It does not copy any file or affect a real agent.</p>`,button('Cancel','close','','','')+button('Copy registry version','apply-skill',value,'primary','copy'));}
function inspectNote(id){const n=notes.find(n=>n.id===id);if(!n)return;detail(n.title,'OBSIDIAN / DEMO NOTE',`<p>${esc(n.folder)} · ${esc(n.time)}${n.pinned?' · Important':''}</p><div class="note-preview-text">${esc(n.body)}</div>`,button(n.pinned?'Unpin note':'Pin note','pin-detail',id,'','pin')+button('Export .md','export-note',id,'','download')+(['combat','harness'].includes(n.id)?button('Append idea','capture',n.id,'primary','bulb'):''));}
function attention(){detail('Two decisions need you.','ATTENTION / FICTIONAL SCENARIO',`<div class="activity-list">${events.slice(0,2).map(e=>`<article class="event-row"><span>${icon(e.icon)}</span><div><h3>${e.title}</h3><p>${e.body}</p></div><time>${e.time}</time></article>`).join('')}</div>`,button('Review activity','go','activity','primary','clock'));}
function openIdea(target='new'){closeDialogs();$('#idea-form').reset();$('#idea-target').value=['harness','combat'].includes(target)?target:'new';$('#idea-dialog').showModal();$('#idea-title').focus();}
function exportNote(id){const n=notes.find(n=>n.id===id);if(!n)return;const blob=new Blob([`# ${n.title}\n\n> Exported from the HARNESS mockup. Not synced to Obsidian.\n\n${n.body}\n`],{type:'text/markdown;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=n.title.replace(/[^a-z0-9 -]/gi,'').slice(0,70)+'.md';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function configCopyReview(){const l=config(state.left),r=config(state.right);const sameRuntime=l.Runtime===r.Runtime;detail('Review settings copy','CONFIGURATION / EXPLICIT DEMO ACTION',`<p>From <strong>${esc(state.left)}</strong> to <strong>${esc(state.right)}</strong>.</p><pre class="code-preview">${esc(['Model','Reasoning','Browser'].map(k=>`${k}: ${r[k]} → ${l[k]}`).join('\n'))}</pre><p>${sameRuntime?'Compatible runtime in this fictional example.':'The runtimes differ. Cross-runtime copying is intentionally disabled in this demo.'}</p><p class="demo-notice">Only the three preferences shown above can be copied. Runtime, profile identity, permissions, hooks and skill files are untouched. No real configuration is written.</p>`,button('Cancel','close')+(sameRuntime&&state.left!==state.right?button('Apply to demo','apply-config','','primary','check'):''));}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('visible'),4200);}
const actions={
 go,agent:inspectAgent,machine:inspectMachine,project:inspectProject,tool:inspectTool,skill:inspectSkill,note:inspectNote,attention,capture:openIdea,notice:toast,close:closeDialogs,
 'work-filter':id=>{state.workFilter=id;render();},'agent-filter':id=>{state.agentFilter=id;render();},'note-filter':id=>{state.noteFilter=id;render();},
 pin:id=>{const n=notes.find(n=>n.id===id);if(n){n.pinned=!n.pinned;render();}},
 'pin-detail':id=>{const n=notes.find(n=>n.id===id);if(n){n.pinned=!n.pinned;render();inspectNote(id);}},
 'export-note':exportNote,
 'compare-agent':id=>{state.right=id;go('settings');},
 'apply-skill':value=>{const [id,k]=value.split('|');if(skillStates[id]&&skills[Number(k)]){skillStates[id][Number(k)]='same';closeDialogs();render();toast('Registry version copied to the demo cell. No agent files changed.');}},
 swap:()=>{[state.left,state.right]=[state.right,state.left];render();},
 raw:()=>detail('Raw configuration comparison','CONFIGURATION / DEMO JSON',`<pre class="code-preview">${esc(JSON.stringify({source:{agent:state.left,settings:config(state.left)},target:{agent:state.right,settings:config(state.right)}},null,2))}</pre>`),
 'copy-config':configCopyReview,
 'apply-config':()=>{const src=config(state.left),dst=config(state.right);if(src.Runtime!==dst.Runtime)return;configOverrides[state.right]={...configOverrides[state.right],Model:src.Model,Reasoning:src.Reasoning,Browser:src.Browser};closeDialogs();render();toast('Three preferences updated in the demo only. No configuration files were written.');}
};
document.addEventListener('click',e=>{const close=e.target.closest('[data-close]');if(close){document.getElementById(close.dataset.close)?.close();return;}const el=e.target.closest('[data-action]');if(el&&actions[el.dataset.action])actions[el.dataset.action](el.dataset.id||'');});
document.addEventListener('change',e=>{if(e.target.id==='compare-left'){state.left=e.target.value;render();}if(e.target.id==='compare-right'){state.right=e.target.value;render();}});
document.addEventListener('input',e=>{if(e.target.id==='notes-search'){state.noteQuery=e.target.value;$('#notes-list').innerHTML=notesList();}});
$('#idea-form').addEventListener('submit',e=>{e.preventDefault();const title=$('#idea-title').value.trim(),body=$('#idea-body').value.trim();if(!title||!body)return;const target=$('#idea-target').value;const existing=notes.find(n=>n.id===target);if(existing){existing.body+='\n\n## '+title+'\n\n'+body;existing.time='Just now';notes=[existing,...notes.filter(n=>n!==existing)];state.noteFilter='latest';}else{notes.unshift({id:'idea-'+Date.now(),title,body,folder:'00 Inbox',time:'Just now',pinned:false,type:'idea'});state.noteFilter='ideas';}state.noteQuery='';go('knowledge');toast(existing?'Idea appended to the demo note. Nothing was written to Obsidian.':'Idea added to this tab’s demo notes. Export it before reloading.');});
$('#capture-trigger').addEventListener('click',()=>openIdea());$('#notifications').addEventListener('click',attention);
$('#atmosphere').addEventListener('click',()=>{const on=document.body.classList.toggle('calm');$('#atmosphere').setAttribute('aria-pressed',String(on));$('#atmosphere').setAttribute('aria-label',on?'Restore decorative glow':'Reduce decorative glow');});
$('#menu-button').addEventListener('click',()=>{const on=$('#sidebar').classList.toggle('open');$('#menu-button').setAttribute('aria-expanded',String(on));});
document.addEventListener('click',e=>{if(innerWidth<=480&&$('#sidebar').classList.contains('open')&&!e.target.closest('#sidebar,#menu-button')){$('#sidebar').classList.remove('open');$('#menu-button').setAttribute('aria-expanded','false');}});
let commandItems=[];
function commandEntries(){return [...projects.map(p=>({label:p.name,kind:'Project',icon:'folder',action:'project',id:p.id})),...tools.map(t=>({label:t.name,kind:'Tool / '+t.role,icon:t.icon,action:'tool',id:t.id})),...nav.map(([id,i,label])=>({label,kind:'View',icon:i,action:'go',id})),{label:'Capture an idea',kind:'Obsidian · demo',icon:'bulb',action:'capture',id:''},...agents.map(a=>({label:a.id,kind:machineFor(a.machine).name+' / '+a.runtime,icon:'cube',action:'agent',id:a.id})),...machines.map(m=>({label:m.name,kind:'Machine',icon:m.icon,action:'machine',id:m.id})),...notes.map(n=>({label:n.title,kind:'Note / '+n.folder,icon:'book',action:'note',id:n.id})),...skills.map((s,k)=>({label:s.id,kind:'Skill registry',icon:'skill',action:'skill',id:'unity-01|'+k}))];}
function renderCommands(){const q=$('#command-input').value.trim().toLowerCase();const entries=commandEntries();commandItems=(q?entries.filter(x=>(x.label+' '+x.kind).toLowerCase().includes(q)):entries.filter(x=>x.kind==='View'||x.action==='capture')).slice(0,q?15:10);state.commandIndex=Math.min(state.commandIndex,Math.max(0,commandItems.length-1));$('#command-results').innerHTML=commandItems.map((x,k)=>`<button class="command-result ${k===state.commandIndex?'active':''}" data-command-index="${k}">${icon(x.icon)}<span>${esc(x.label)}</span><small>${esc(x.kind)}</small></button>`).join('')||'<p class="empty-state">No matching demo records.</p>';}
function openCommands(){closeDialogs();$('#command-input').value='';state.commandIndex=0;renderCommands();$('#command-dialog').showModal();$('#command-input').focus();}
function runCommand(k){const entry=commandItems[k];if(!entry)return;$('#command-dialog').close();actions[entry.action](entry.id);}
$('#search-trigger').addEventListener('click',openCommands);$('#command-input').addEventListener('input',()=>{state.commandIndex=0;renderCommands();});
$('#command-results').addEventListener('click',e=>{const b=e.target.closest('[data-command-index]');if(b)runCommand(Number(b.dataset.commandIndex));});
$('#command-input').addEventListener('keydown',e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const length=commandItems.length||1;state.commandIndex=(state.commandIndex+(e.key==='ArrowDown'?1:-1)+length)%length;renderCommands();$('#command-results .active')?.scrollIntoView({block:'nearest'});}if(e.key==='Enter'){e.preventDefault();runCommand(state.commandIndex);}});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommands();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='i'){e.preventDefault();openIdea();}if(e.key==='Escape'){$('#sidebar').classList.remove('open');$('#menu-button').setAttribute('aria-expanded','false');}});
for(const d of document.querySelectorAll('dialog')){d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});}
state.view=pageRenderers[location.hash.slice(1)]?location.hash.slice(1):'overview';render();
